export {default as Pizza} from './Pizza'
export {default as NotFound} from './NotFound'
export {default as Login} from './Login'
export {default as Home} from './Home'
export {default as Cart} from './Cart'
export {default as Register} from './Register'